// у системы статусов пока нет применения, оно просто существует

export const game_achievements = [
    { min: 1,      
      max: 999,    
      status: "10" 
    },
    { min: 1000,   
      max: 4999,   
      status: "9" 
    },
    { min: 5000,   
      max: 9999,   
      status: "8" 
    },
    { min: 10000,  
      max: 24999,  
      status: "7" 
    },
    { min: 25000,  
      max: 49999,  
      status: "6" 
    },
    { min: 50000,  
      max: 74999,  
      status: "5" 
    },
    { min: 75000,  
      max: 89999,  
      status: "4" 
    },
    { min: 90000,  
      max: 94999,  
      status: "3" 
    },
    { min: 95000,  
      max: 99999,  
      status: "2" 
    },
    { min: 100000, 
      max: 100000, 
      status: "1" 
    }
];

export const game_settings = [
    { name: "minimumForEnabled",  
      count: 1,          
      status: "человек" 
    },
    { name: "maximumForDisabled", 
      count: 1000000000, status: 
      "Вы достигли максимума!", 
      color: "red" 
    }
]

export const upgrades = [
    { name:         "dirt",
      unlocked:     true,
      free:         true,
      lockedIcon:   "LockOffDirt",
      UnlockedIcon: "LockOnDirt",
      priceTitle:   "DirtButtonPrice",
      Opisanie:     "OpisanieButtonDirt",
      Sound:        "dirt.mp3",
      money:         0,
      powerMoney:    1,
      userPower:     1,
      color:        "radial-gradient(circle, rgba(190, 105, 35, 0.55), rgba(65, 30, 10, 0.8)), url('./Images/Buttons/dirt.avif')"
    },
    { name:         "water",    
      unlocked:     false,
      free:         false, 
      lockedIcon:   "LockOffWater", 
      UnlockedIcon: "LockOnWater", 
      priceTitle:   "WaterButtonPrice",
      Opisanie:     "OpisanieButtonWater",
      Sound:        "water.mp3", 
      money:         500,   
      powerMoney:    100,  
      userPower:     10, 
      color:        "radial-gradient(circle, rgba(60, 150, 190, 0.55), rgba(15, 45, 65, 0.8)), url('./Images/Buttons/water.avif')"
    },
    { name:         "wood",    
      unlocked:     false,
      free:         false, 
      lockedIcon:   "LockOffWood", 
      UnlockedIcon: "LockOnWood", 
      priceTitle:   "WoodButtonPrice",
      Opisanie:     "OpisanieButtonWood",
      Sound:        "wood.mp3", 
      money:         10000,   
      powerMoney:    150,  
      userPower:     20, 
      color:        "radial-gradient(circle, rgba(150, 95, 45, 0.55), rgba(65, 35, 15, 0.8)), url('./Images/Buttons/wood.avif')"
    },
    { name:         "gold",  
      unlocked:     false, 
      free:         false, 
      lockedIcon:   "LockOffGold", 
      UnlockedIcon: "LockOnGold", 
      priceTitle:   "GoldButtonPrice",
      Opisanie:     "OpisanieButtonGold", 
      Sound:        "gold.mp3",
      money:         50000,  
      powerMoney:    200, 
      userPower:     30, 
      color:        "radial-gradient(circle, rgba(210, 165, 45, 0.55), rgba(75, 50, 10, 0.8)), url('./Images/Buttons/gold.avif')"
    },
    { name:         "amethyst",    
      unlocked:     false, 
      free:         false, 
      lockedIcon:   "LockOffAmethyst", 
      UnlockedIcon: "LockOnAmethyst", 
      priceTitle:   "AmethystButtonPrice",
      Opisanie:     "OpisanieButtonAmethyst",
      Sound:        "amethyst.mp3", 
      money:         100000,  
      powerMoney:    250, 
      userPower:     40, 
      color:        "radial-gradient(circle, rgba(155, 75, 190, 0.55), rgba(50, 15, 65, 0.8)), url('./Images/Buttons/amethyst.avif')"
    },
    { name:         "metal",    
      unlocked:     false, 
      free:         false, 
      lockedIcon:   "LockOffMetal", 
      UnlockedIcon: "LockOnMetal", 
      priceTitle:   "MetalButtonPrice",
      Opisanie:     "OpisanieButtonMetal",
      Sound:        "metal.mp3", 
      money:         150000,  
      powerMoney:    300, 
      userPower:     50, 
      color:        "radial-gradient(circle, rgba(166, 105, 65, 0.38), rgba(55, 48, 43, 0.88)), url('./Images/Buttons/metal.avif')"
    },
    { name:         "circuit", 
      unlocked:     false,
      free:         false,  
      lockedIcon:   "LockOffCircuit", 
      UnlockedIcon: "LockOnCircuit", 
      priceTitle:   "CircuitButtonPrice",
      Opisanie:     "OpisanieButtonCircuit",
      Sound:        "circuit.mp3", 
      money:         200000, 
      powerMoney:    350, 
      userPower:     60, 
      color:        "radial-gradient(circle, rgba(25, 170, 160, 0.55), rgba(20, 30, 55, 0.85)), url('./Images/Buttons/circuit.avif')"
    },
    { name:         "obsidian",    
      unlocked:     false, 
      free:         false, 
      lockedIcon:   "LockOffObsidian", 
      UnlockedIcon: "LockOnObsidian", 
      priceTitle:   "ObsidianButtonPrice",
      Opisanie:     "OpisanieButtonObsidian",
      Sound:        "obsidian.mp3", 
      money:         250000,  
      powerMoney:    400, 
      userPower:     70, 
      color:        "radial-gradient(circle, rgba(90, 100, 115, 0.5), rgba(15, 18, 22, 0.85)), url('./Images/Buttons/obsidian.avif')"
    },
    { name:         "lava", 
      unlocked:     false,
      free:         false,  
      lockedIcon:   "LockOffLava", 
      UnlockedIcon: "LockOnLava", 
      priceTitle:   "LavaButtonPrice",
      Opisanie:     "OpisanieButtonLava",
      Sound:        "lava.mp3", 
      money:         300000, 
      powerMoney:    450, 
      userPower:     80, 
      color:        "radial-gradient(circle, rgba(230, 65, 20, 0.55), rgba(75, 10, 5, 0.85)), url('./Images/Buttons/lava.avif')"
    },
    { name:         "space", 
      unlocked:     false,
      free:         false,  
      lockedIcon:   "LockOffSpace", 
      UnlockedIcon: "LockOnSpace", 
      priceTitle:   "SpaceButtonPrice",
      Opisanie:     "OpisanieButtonSpace",
      Sound:        "space.mp3", 
      money:         350000, 
      powerMoney:    500, 
      userPower:     90, 
      color:        "radial-gradient(circle, rgba(75, 105, 180, 0.55), rgba(20, 15, 55, 0.85)), url('./Images/Buttons/space.avif')"
    },
    { name:         "rainbow", 
      unlocked:     false, 
      free:         false, 
      lockedIcon:   "LockOffRainbow", 
      UnlockedIcon: "LockOnRainbow", 
      priceTitle:   "RainbowButtonPrice",
      Opisanie:     "OpisanieButtonRainbow",
      Sound:        "rainbow.mp3", 
      money:         400000, 
      powerMoney:    550, 
      userPower:     100, 
      color:        ""
    }
];